pcetc/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :storekeepers, 
              controllers: { sessions: 'storekeepers/sessions', registrations: 'storekeepers/registrations', confirmations: 'storekeepers/confirmations', passwords: 'storekeepers/passwords', unlocks: 'storekeepers/unlocks'  }, 
              path: 'lojistas', 
              path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'nova_senha', confirmation: 'confirmar', unlock: 'desbloquear', registration: 'cadastro', sign_up: 'novo' }

end

pcetc/app/models/category.rb
class Category < ActiveRecord::Base
end

pcetc/app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :category
  belongs_to :vendor

  searchkick text_start: [‘name’]

end

pcetc/app/models/storekeeper.rb
class Storekeeper < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, :lockable
end

pcetc/app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

pcetc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

pcetc/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

pcetc/app/controllers/storekeepers/confirmations_controller.rb
class Storekeepers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

pcetc/app/controllers/storekeepers/omniauth_callbacks_controller.rb
class Storekeepers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

pcetc/app/controllers/storekeepers/passwords_controller.rb
class Storekeepers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

pcetc/app/controllers/storekeepers/registrations_controller.rb
class Storekeepers::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

layout 'application', only: [:edit]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

pcetc/app/controllers/storekeepers/sessions_controller.rb
class Storekeepers::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

pcetc/app/controllers/storekeepers/unlocks_controller.rb
class Storekeepers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

pcetc/app/helpers/application_helper.rb
module ApplicationHelper
end

pcetc/app/helpers/home_helper.rb
module HomeHelper
end

pcetc/app/views/home/_sign_in.html.erb
<div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="margin-top: 50px;">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius: 0;">
      <div class="modal-header" style="background-color: #38a4dd; color: #ffffff; text-transform: uppercase; font-weight: 600;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Área do lojista</h4>
      </div>
      <div class="modal-body">
        <div class="container" style="width: 100%; padding-top: 15px;">
          <!-- <button class="btn btn-lg btn-primary" style="width: 100%; background-color: #4267B2; margin: 10px 0 10px 0;">
            <span class="pull-left"><img src="FB-f-Logo__white_29.png" style="width: 32px; height: 32px;" /></span><span style="margin-left: -22px; line-height: 175%;">Entrar com Facebook</span>
          </button>
          <button class="btn btn-lg btn-default" style="width: 100%; margin: 10px 0 0 0;">
            <span class="pull-left"><img src="g-logo.png" style="width: 32px; height: 32px;" /></span><span style="margin-left: -22px; line-height: 175%;">Entrar com Google</span>
          </button>
          <hr> -->
          <%= form_for Storekeeper.new, as: :storekeeper, url: storekeeper_session_path, method: "POST", class: "form-group" do |f| %>
            <label for="inputEmail" class="sr-only">Email</label>
            <!-- <input type="email" id="inputEmail" class="form-control input-lg" placeholder="Email" required autofocus> -->
            <%= f.email_field :email, autofocus: true, required: true, class: "form-control input-lg", placeholder: "Email" %>
            <br>
            <label for="inputPassword" class="sr-only">Senha</label>
            <!-- <input type="password" id="inputPassword" class="form-control input-lg" placeholder="Senha" required> -->
            <%= f.password_field :password, autocomplete: "off", required: true, class: "form-control input-lg", placeholder: "Senha" %>
            <div class="checkbox">
              <label>
                <input type="checkbox" value="remember-me"> Lembrar-se de mim
              </label>
            </div>
            <!-- <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button> -->
            <%= f.submit "Entrar", class: "btn btn-lg btn-primary btn-block" %>
          <% end %>
          <p><a href="#">Esqueci minha senha...</a></p>
          <p>Ainda não possui uma conta para sua loja? <%= link_to "Cadastre-se!", new_storekeeper_registration_path %></p>
        </div> <!-- /container -->
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Login</button>
      </div> -->
    </div>
  </div>
</div>

pcetc/app/views/home/index.html.erb
<nav class="navbar navbar-default navbar-static-top" style="height: 70px; margin: 0; background-color: #38a4dd; color: #ffffff; border: 0;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <span style="font-size: 37px; line-height: 47px; font-weight: 700; color: #ffffff;">PC<span style="color: rgba(255,255,255,0.8);">&ETC</span></span>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#" data-toggle="dropdown" class="dropdown-toggle" style="color: #ffffff;">Categorias <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <div class="row">
              <div class="col-md-6">
                <li class="dropdown-header">PC</li>
                <li><a href="#">Processadores</a></li>
                <li><a href="#">Placas-mãe</a></li>
                <li><a href="#">Memórias</a></li>
                <li><a href="#">Placas de vídeo</a></li>
                <li><a href="#">Armazenamento</a></li>
                <li><a href="#">Monitores</a></li>
                <li><a href="#">Gabinetes</a></li>
                <li><a href="#">Fontes</a></li>
                <li><a href="#">Acessórios</a></li>
                <li><a href="#">Software</a></li>
              </div>
              <div class="col-md-6">
                <li class="dropdown-header">ETC</li>
                <li><a href="#">Games</a></li>
                <li><a href="#">Celulares</a></li>
                <li><a href="#">Tablets</a></li>
                <li><a href="#">Laptops</a></li>
                <li><a href="#">Desktops</a></li>
                <li><a href="#">Redes</a></li>
                <li><a href="#">Câmeras</a></li>
                <li><a href="#">Impressoras</a></li>
                <li><a href="#">Capas</a></li>
                <li><a href="#">Serviços</a></li>
              </div>
            </div>
          </ul>
        </li>
        <!-- <li class="active"><a href="/blog">Home</a></li> -->
        <li><a href="#lojistas">Lojas</a></li>
        <!-- <li><a href="#ofertas">Ofertas</a></li> -->
        <li><a href="#comofunciona">Como funciona?</a></li>
        <li><a href="#cadastro">Cadastre sua loja!</a></li>
        <!-- <li><a href="http://blog.pcetc.com.br" class="navbar-link">Blog</a></li> -->
        <!-- <li><a href="#configurador" style="color: #38A4DD;">CONFIGURE SEU PC</a></li> -->
        <!-- <li><a href="#lojistas" class="navbar-link">Lojistas</a></li> -->
        <!-- <li><a href="#usuarios" class="navbar-link" data-toggle="modal" data-target="#modalLogin">Login</a></li> -->
        <!-- <li><a href="#blog">Blog</a></li> -->
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

<div class="fill">
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron" id="jumbo" style="background-color: #38a4dd; color: #ffffff; padding-top: 45px; padding-bottom: 30px; margin-bottom: 0;">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 style="font-size: 37px; line-height: 150%; margin-top: 0px;">Pesquise preços de produtos de informática <br>sem sair de casa</h1>
          <form class="form-inline" style="margin: 25px 0;">
            <div class="input-group">
              <input type="text" size="60" class="form-control input-lg" placeholder="Pesquise por componente ou produto" style="border: 1px #ffffff;">
              <span class="input-group-btn">
                <button class="btn btn-lg btn-primary" type="button"><i class="glyphicon glyphicon-search" style="border: 1px solid #337ab7;"></i></button>
              </span>
            </div>
          </form>
          <p style="color: #eeeeee; font-weight: 100; font-size: 18px;">na Santa Ifigênia, 25 de Março, Shopping Avenida Central e muito mais!</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row" style="background-color: #ffffff; padding-top: 30px;">
  <div class="container">
    <div class="panel panel-default" style="border: 0;">
      <!-- <div class="panel-heading">
        <h3 class="panel-title">Peças de computador</h3>
      </div> -->
      <div class="panel-body">
        <ul class="list-inline text-center" style="font-size: 14px;">
          <li>
          	<a href="#"><%= image_tag("nav-cpu.jpg", size: "96x96", alt: "Processadores") %><br>Processadores</a>
          </li>
          <li>
          	<a href="#"><%= image_tag("nav-motherboards.jpg", size: "96x96", alt: "Placas-mãe") %><br>Placas-mãe</a>
          </li>
          <li>
          	<a href="#"><%= image_tag("nav-memory.png", size: "96x96", alt: "Memórias") %><br>Memórias</a>
          </li>
          <li><a href="#"><%= image_tag("nav-videocard.jpg", size: "96x96", alt: "Placas de vídeo") %><br>Placas de vídeo</a></li>
          <li><a href="#"><%= image_tag("nav-storage.jpg", size: "96x96", alt: "Armazenamento") %><br>Armazenamento</a></li>
          <li><a href="#"><%= image_tag("nav-displays.jpg", size: "96x96", alt: "Monitores") %><br>Monitores</a></li>
          <li><a href="#"><%= image_tag("nav-case.jpg", size: "96x96", alt: "Gabinetes") %><br>Gabinetes</a></li>
          <li><a href="#"><%= image_tag("nav-powersupply.jpg", size: "96x96", alt: "Fontes") %><br>Fontes</a></li>
          <li><a href="#"><%= image_tag("nav-accessories.jpg", size: "96x96", alt: "Acessórios") %><br>Acessórios</a></li>
          <li><a href="#"><%= image_tag("nav-software.jpg", size: "96x96", alt: "Software") %><br>Software</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row" style="background-color: #ffffff;">
  <div class="container">
    <div class="panel panel-default" style="border: 0;">
      <!-- <div class="panel-heading">
        <h3 class="panel-title">Eletroeletrônicos</h3>
      </div> -->
      <div class="panel-body">
        <ul class="list-inline text-center" style="font-size: 14px;">
          <li><a href="#"><%= image_tag("nav-consoles.jpg", size: "96x96", alt: "Games") %><br>Games</a></li>
          <li><a href="#"><%= image_tag("nav-smartphones.jpg", size: "96x96", alt: "Celulares") %><br>Celulares</a></li>
          <li><a href="#"><%= image_tag("nav-tablets.jpg", size: "96x96", alt: "Tablets") %><br>Tablets</a></li>
          <li><a href="#"><%= image_tag("nav-laptops.jpg", size: "96x96", alt: "Laptops") %><br>Laptops</a></li>
          <li><a href="#"><%= image_tag("nav-computers.jpg", size: "96x96", alt: "Desktops") %><br>Desktops</a></li>
          <li><a href="#"><%= image_tag("nav-networks.jpg", size: "96x96", alt: "Redes") %><br>Redes</a></li>
          <li><a href="#"><%= image_tag("nav-cameras.jpg", size: "96x96", alt: "Câmeras") %><br>Câmeras</a></li>
          <li><a href="#"><%= image_tag("nav-printers.jpg", size: "96x96", alt: "Impressoras") %><br>Impressoras</a></li>
          <li><a href="#"><%= image_tag("nav-covers.jpg", size: "96x96", alt: "Capas") %><br>Capas</a></li>
          <li><a href="#"><%= image_tag("nav-tools.jpg", size: "96x96", alt: "Serviços") %><br>Serviços</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row" style="background-color: #ffffff;">
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Lojas</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-2">
          <%= image_tag("loja-1.gif", alt: "Loja Um") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("loja-2.gif", alt: "Loja Dois") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("loja-3.gif", alt: "Loja Três") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("loja-4.gif", alt: "Loja Quatro") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("loja-5.gif", alt: "Loja Cinco") %>
        </div>
        <div class="col-md-2">
          <%= image_tag("loja-6.gif", alt: "Loja Seis") %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row" style="background-color: #ffffff;">
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Melhores ofertas</h3>
      </div>
      <div class="panel-body">
        
      </div>
    </div>
  </div>
</div>

<div class="row" style="background-color: #ffffff;">
  <div class="container">
    <div class="panel panel-default" style="border: 0;">
      <div class="panel-heading" style="background-color: #ffffff;">
        <h3 class="panel-title">Vantagens de pesquisar preços pelo PC&ETC</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-6">
          <h4>Para o consumidor</h4>
          <p>Lorem ipsum donorum ipsis literis onminia vincit.</p>
        </div>
        <div class="col-md-6">
          <h4>Para o lojista</h4>
          <p>Lorem ipsum donorum ipsis literis onminia vincit.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row" style="background-color: #ffffff;">
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Dicas e tutoriais</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-3">
          <h5>Teste Um</h5>
          <p>Lorem ipsum donorum ipsis literis onminia vincit.</p>
        </div>
        <div class="col-md-3">
          <h5>Teste Dois</h5>
          <p>Lorem ipsum donorum ipsis literis onminia vincit.</p>
        </div>
        <div class="col-md-3">
          <h5>Terceiro teste</h5>
          <p>Lorem ipsum donorum ipsis literis onminia vincit.</p>
        </div>
        <div class="col-md-3">
          <h5>Quarto teste</h5>
          <p>Lorem ipsum donorum ipsis literis onminia vincit.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

<!-- Login Modal -->
<%= render "sign_in" %>

pcetc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt_BR">
<head>
  <title>PC&ETC</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link type='text/css' href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,300,300italic,700,700italic' rel='stylesheet'>
</head>
<body>

<%= yield %>

</body>
</html>

pcetc/app/views/storekeepers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>